gWaitText_HowLongToWait::
	.string "It is currently {COLOR RED}{STR_VAR_1}{COLOR DARK_GREY}).\n"
	.string "How long would you like to wait?$"
	
gWaitText_YouCantWaitNow::
	.string "You can't wait right now.$"
	
gWaitText_WaitingTooOften::
	.string "You've waited for too long! Keep going\n"
	.string "to recharge your wait time.$"

gWaitText_HoursRemaining::
	.string "TIME LEFT:\n"
	.string "{COLOR RED}{STR_VAR_2}$"
	
gWaitText_Hour::
	.string "HOUR$"

gWaitText_Space::
	.string " $"
	
gWaitText_S::
	.string "S$"
	
gWaitText_NotEnoughTime::
	.string "You can't wait for that long. Would you\n"
	.string "like to wait for as long as possible?$"
